package com.example.carschool.model;

public enum NotificationType {
    CLASS_FINISHED,
    CLASS_SCHEDULED,
    CLASS_CANCELLED,
    CLASS_REQUEST_ACCEPTED,
    CLASS_REQUEST_DENIED,
    LAST_CLASS_REMINDER,
    INSTRUCTOR_ON_LEAVE,
    EXAM_SCHEDULED,
    EXAM_CANCELLED,
    EXAM_PASS,
    EXAM_FAIL,
    TIME_PREF_REMINDER,

    CLASS_CANCELLED_BY_CANDIDATE,
    NEW_CLASS_REQUEST,
    WEEKLY_SCHEDULE_REMINDER,
    CAR_FIXED,
    INSTRUCTOR_VEHICLE_REQUEST_ACCEPTED,
    INSTRUCTOR_VEHICLE_REQUEST_DENIED,
    INSTRUCTOR_LEAVE_REQUEST_ACCEPTED,
    INSTRUCTOR_LEAVE_REQUEST_DENIED,
    NEW_CAR_ASSIGNED,
    RESERVE_ASSIGNED
}
